### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by Djam94800** [keikai/keikai#2]
Hello,

Unable to install the application. I have an error :

`[ERROR] Failed to execute goal on project keikai-model-oss: Could not resolve dependencies for project io.keikai:keikai-model-oss:jar:5.0.0-Beta1: Could not find artifact org.zkoss.common:zcommon:jar:8.0.5 in CE (http://mavensync.zkoss.org/maven2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project keikai-model-oss: Could not resolve dependencies for project io.keikai:keikai-model-oss:jar:5.0.0-Beta1: Could not find artifact org.zkoss.common:zcommon:jar:8.0.5 in CE (http://mavensync.zkoss.org/maven2)`

how to fix the problem ?

Thanks

**Comment by cor3000** [comment]
8.0.5 is not available for CE, the latest 8.0.x version for CE is 8.0.2.2 as referenced in the parent pom

https://mavensync.zkoss.org/maven2/io/keikai/parent/keikai-build-oss/5.0.1-Beta/keikai-build-oss-5.0.1-Beta.pom

can you  please point out, where 8.0.5 is referenced?

**Comment by cor3000** [comment]
I just noticed the zpoi dependency still loads 8.0.5 transitively, 

you can check this via `mvn dependency:tree`

To fix this you can add this to the parent pom.xml for now

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.zkoss.common</groupId>
                <artifactId>zcommon</artifactId>
                <version>${zk.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by Djam94800** [comment]
Great !

But another error  

`[ERROR] Failed to execute goal on project keikai-app-oss: Could not resolve dependencies for project io.keikai:keikai-app-oss:war:5.0.0-Beta1: Failure to find org.zkoss.zk:zkex:jar:8.0.2.2-                                                                                  Eval in http://mavensync.zkoss.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of EE has elapsed or updates are forced -> [Help 1 `

`[INFO] Keikai Spreadsheet Build ........................... SUCCESS [  1.184 s]
[INFO] Keikai Spreadsheet Model ........................... SUCCESS [  2.673 s]
[INFO] Keikai Spreadsheet ................................. SUCCESS [  0.690 s]
[INFO] Keikai Spreadsheet App ............................. FAILURE [  0.466 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
`

**Comment by hawkchen** [comment]
Please get updated tutorial project (5.0.0-Beta2) from the repo.

**Comment by Djam94800** [comment]
Great Job !!!

Thanck very much.
