### ISSUE TITLE
 No plugin found for prefix 'jetty' in the current project and in the plugin groups

### ISSUE THREAD

**Issue by pwaicode** [keikai/keikai#3]
$ mvn jetty:run -pl kkapp -am

[ERROR] No plugin found for prefix 'jetty' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/weaver/.m2/repository), snapshots (http://snapshots.maven.codehaus.org/maven2), central (http://repo1.maven.org/maven2), ZK Repository (http://mavensync.zkoss.org/maven2)] -> [Help 1]

**Comment by cor3000** [comment]
PR: https://github.com/keikai/keikai/pull/4

**Comment by hawkchen** [comment]
solved it by pull request #4
