### ISSUE TITLE
Add feature to select more cells with CTRL key like Excel

### ISSUE THREAD

**Issue by emilianooddo** [keikai/keikai#8]
Hi,
I tried to use the keikay library, but I saw that there isn't any possibility to select more cells non-contiguous with CTRL key pressed, like in Microsoft Excel.
Do you thinking of developing this feature?

thanks

**Comment by hawkchen** [comment]
Thanks for your suggestions. Please follow the link https://tracker.zkoss.org/browse/KEIKAI-429
